### ISSUE TITLE
Error: 401 (Unauthorized)

### ISSUE THREAD

**Issue by jarnohenneman** [davemaple/aws-lambda-hipchat#2]
When running the Lambda function as described in the readme file I receive an 401 (Unauthorized).

The config.apiAuthToken is generated by going to;
Account Settings > API Access > Send Notification > Generate Token.

Any idea how to resolve this?

```
Error: 401 (Unauthorized) - Auth token invalid. Please see: https://www.hipchat.com/docs/api/auth
    at Rooms.BaseClass.throwError (/var/task/node_modules/hipchat-client/lib/api/common/base_class.js:19:14)
    at /var/task/node_modules/hipchat-client/lib/api/common/base_class.js:49:35
    at Request.callback (/var/task/node_modules/hipchat-client/node_modules/superagent/lib/node/index.js:729:30)
    at Request.<anonymous> (/var/task/node_modules/hipchat-client/node_modules/superagent/lib/node/index.js:135:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/var/task/node_modules/hipchat-client/node_modules/superagent/lib/node/index.js:906:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
```

**Comment by jarnohenneman** [comment]
The hipchat-client API uses the deprecated V1 API. Was using the wrong key :)
